### ISSUE TITLE
Adding support for xcode 6.4?

### ISSUE THREAD

**Issue by Laurent-Brigaut** [marcinolawski/StoryboardMerge#2]
Hi,

Just tried your tool with xcode 6.4 storyboard and got a crash (findcousin complains that it found more than one cousin for <capability> inside <dependencies>). Are you working on an update?

**Comment by marcinolawski** [comment]
No, I don't actively maintaining the project, but if you send me your storyboard file I will check it

**Comment by Laurent-Brigaut** [comment]
Thanks for answering that fast while you are not maintaining this projetc anymore. Anyway, I will try to give it a shot in my spare time.

**Comment by marcinolawski** [comment]
It should be ok now.
